### ISSUE TITLE
php api doesn't have such annotation as TestCaseID

### ISSUE THREAD

**Issue by Gordiievskyi** [allure-framework/allure-php-api#31]
Hi guys,

Please add such Annotation type to allure-php-adapter-api(not php unit adapter) as java api has
ru.yandex.qatools.allure.annotations.TestCaseId

**Comment by vania-pooh** [comment]
I can just add respective annotation class (pull requests are welcome too). Don't know whether we need any other logic in the API.

**Comment by Gordiievskyi** [comment]
I think there is one more place in Yandex\Allure\Adapter\Annotation\AnnotationManager method processAnnotations() something like this
 elseif ($annotation instanceof Issues) {
                foreach ($annotation->getTestCaseIDs() as $ids) {
                    $this->labels[] = Model\Label::testCaseID($ids);
                }
but for TastCaseID
and so in Yandex\Allure\Adapter\Model\Label new method
Model\Label::testCaseID()
for Yandex\Allure\Adapter\Model\LabelType const ISSUE = 'testCaseId';

**Comment by remorhaz** [comment]
I'm able to use test ID labels in current version (1.2.1), so this issue can be probably safely closed.
