### ISSUE TITLE
More than one annotation @Property

### ISSUE THREAD

**Issue by KorDum** [allure-framework/allure-php-api#37]
```php
/**
 * @Parameter(name = "userId", value = "Идентификатор пользователя")
 * @Parameter(name = "expectedCount", value = "Ожидаемое количество торговых объектов")
 */
public function testFindCorrect($userId, $expectedCount)
```
Ignored first property, only last.

```xml
<parameters>
  <parameter name="expectedCount" value="Ожидаемое количество торговых объектов" kind="argument"/>
</parameters>
```

I think this is because of the library used:
https://github.com/doctrine/annotations/blob/master/lib/Doctrine/Common/Annotations/IndexedReader.php#L72
If replace this on `$annotations[] = $annot;`, all OK.

**Comment by KorDum** [comment]
#38 fixed issue

**Comment by baev** [comment]
fixed via https://github.com/allure-framework/allure-php-api/pull/38
